
# Setup
title:            Blog
tagline:          'Denis Egorov'
paginate:         10
paginate_path:    "page:num"
highlighter:      rouge
future:           false
show_drafts:      false
baseurl:          /test-site
permalink: /:categories/:title:output_ext

author:
  name:           Denis Egorov
  url:            dnegorov.com

# This is the list of pages to include in the header of the website.
pages_list:
  Автор: '/about'
  Архив: '/archive'

plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
